### ISSUE TITLE
feat: Add `asyncio` to `dynamicio`

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [VorTECHsa/dynamicio#16]
## Description
Currently, `dynamicio` does not support `async` behavior.  Enabling support for asynchronous reads and writes can help speed up I/O operations using multithreading. This requires brining in `asyncio` and altering `dynamicio` in a backwards compatible way. 

## Tasks
- [ ] Implement `async_read()` and `async_write()` methods; 
- [ ] Test new behaviour; 
- [ ] Update demo and README.md accordingly;

## Acceptance Criteria
- [ ] All listed tasks are completed;
- [ ] PR is reviewed and approved;
- [ ] A release candidate has been used to read and write from all resources
