### ISSUE TITLE
Design & plan the migration to pandera schemas.

### ISSUE THREAD

**Issue by miodohelper** [VorTECHsa/dynamicio#22]
### Context

As a developer I want to be able to leverage static type checking and exploit the features of my IDE when I interact with dynamicio's resource definitions. At the moment, this is not possible as resource definitions are defined as yamls which are in turn parsed into dictionaries.

- More info can be found in the milestone description [here](https://github.com/VorTECHsa/dynamicio/milestone/2)
- More info on the dynamicio repo can be found 

### Task

Migrating dynamicio to panderas schemas is a chunky milestone. The first task is to plan and create issues that are required in order to complete this milestone.

### Suggested Approach

The [milestone](https://github.com/VorTECHsa/dynamicio/milestone/2) naturally consists of three parts:
1. replace schema
2. pandera validations
3. wrap metrics

### Deliverables & Acceptance Criteria

- [ ] Split the milestone into 6+ mutually exclusive issues.
- [ ] Each issue should be self encapsulated and contain Context, Task, Suggested Approach, Deliverables / Acceptance Criteria, and an Expected Duration (just like this issue).
- [ ] Each issue should adequate information for an engineer to complete the task!
- [ ] 

### Delivery

Please fork this repo, create the issues then, then assign them to @miodohelper when your work is ready for review. Miodo will review the code before sending the PR for a final client review.

_Note: please use the following copy for the newly created issues:_

_Please fork this repo, commit your changes on a branch, then send @miodohelper a PR request when your work is ready for review. Miodo will review the code before sending the PR for a final client review._

### Expected Duration

4 hrs

### Any questions?

Please email `kit.burgess@miodo.io` with any questions you may have 👀
