### ISSUE TITLE
build: Adopt aws cli v2 

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [VorTECHsa/dynamicio#28]
TODO

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. As a [Developer, Analyst, Data Scientist] I would like to [...] when [...]. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Tasks
Clearly state the tasks that one needs to go through to deliver this feature.
- [ ] EDA work: First, we need to investigate [...]
- [ ] Then we need to [...]

## Acceptance Criteria
This feature would have been implemented once:
- [ ] Analysis confirms original assumptions for the improvements [...]
- [ ] Unit tests have been written to confirm the new behaviour [...]
- [ ] Other...

**Comment by VRGhost** [comment]
It appears that AWS CLI v2 was [intentionally](https://github.com/aws/aws-cli/issues/4947) not published to pypi.

And the "awscliv2" library on pypi is using docker to run a container with awscli installed, what is not an acceptable solution for dinamicio.

It appears that the only way to future-proof AWS integration is to use boto3, but that will require a quite significant chunk of code in order to provide i/o throughput comparable to AWS CLI (e.g. a 10-20 Gbps s3 implementation in [metaflow](https://github.com/aws/aws-cli/issues/4947) is ~1.4 kSLOC).
