### ISSUE TITLE
feat: Remove the need for boilerplate classes and use schema name for dataset identification

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [VorTECHsa/dynamicio#5]
### Context

Currently, users of dynamicio are required to create a lot of boilerplate code. [demo/src/io.py](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/demo/src/io.py#L48)

In practice, custom classes that extend UnifiedIO are rarely required.

There's rarely a need for a user to implement the `validate` function. [found here](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/dynamicio/core.py#L205)

We can simplify dynamicio by removing a lot of boilerplate code, (everything below demo/src/io.py IO class)

But, the current implementation is such that the name of the dataset is set to the name of the extension class (like StagedFoo) etc.

- Further details about getting started with dynamicio can be found [here](https://youtu.be/Feh6KyrsFQI) 
- Further details about this task can be found [here](https://youtu.be/Cqpf022S3ic) 

### Task

- [ ] Remove validate method from [core.py](https://github.com/miodo/dynamicio/blob/369478547363f00bb2d0ecbb9737456d931fbabf/dynamicio/core.py#L205)
- [ ] Name io.py/line 173 don't use class name here anymore, use name from schema file.
### Suggested Approach

- Replace references of class name with references to schema config name.
- Remove `def validate` method, as described in video.

### Acceptance Criteria

- [ ] dynamicio uses the schema name rather than extension class name
- [ ] `io.py` boilerplate code not required anymore, as discussed in video
- [ ] all references to `validate` method are to be removed.
- [ ] all existing tests pass
- [ ] new tests written as required
- [ ] readme & docs are updated to reflect the new changes.

### Delivery

Please create a new branch and open up a PR . When the task is complete, please request a review from @miodohelper !

### Expected Duration
3hrs

### Any questions?

Please email `kit.burgess@miodo.io` with any questions you may have 👀
